ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;



DROP USER ADMIN_FIT_2026 CASCADE;
CREATE USER ADMIN_FIT_2026
IDENTIFIED BY ADMIN_FIT_2026

DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP;
ALTER USER ADMIN_FIT_2026 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO ADMIN_FIT_2026;
GRANT "RESOURCE" TO ADMIN_FIT_2026;
ALTER USER ADMIN_FIT_2026 DEFAULT ROLE "RESOURCE";





